before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: checksums.txt
source:
  enabled: true
release:
  prerelease: allow
  draft: true # allow for manual edits
  github:
    owner: benmoss
    name: gh-release-installer
